# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d61c3609737508232ab2f6d5af01bd8afc30669407f16a38539218311ee606383adceccfa92ededa535fc9371b72b06c7a131f1f94ee78671b549695db0f102

test:
  secret_key_base: 65dd862c50b586197bd0ab0d1956878727e49515944005aed1ec54765377058a3a080d46014506e299fda5945f85c2cc15f5df7eda5efc776998a968323cadbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
